version: '3'

services:
    vizfixer-nginx:
        build: ./nginx
        container_name: vizfixer-nginx
        ports:
            - 8007:80
        depends_on: 
            - vizfixer

    vizfixer:
        build: ./server
        container_name: vizfixer
        command: gunicorn -c gunicorn.py app:app
        ports:
            - 6040:6040
