RuleIntro = {
    "enc_type_valid_1": "Primitive type has to support data type. fieldtype应该是数据的类型：字符 布尔等",
    "enc_type_valid_2": "Primitive type has to support data type.",
    "bin_q_o": "Can only bin quantitative or ordinal.",
    "log_q": "Can only use log with quantitative.",
    "zero_q": "Can only use zero with quantitative.",
    "log_discrete": "Cannot use log scale with discrete (which includes binned).",
    "log_zero": "Cannot use log and zero together.",
    "log_non_positive": "Cannot use log if the data is negative or zero.",
    "bin_and_aggregate": "Cannot bin and aggregate.",
    "aggregate_o_valid": "Oridnal only supports min, max, and median.",
    "aggregate_t_valid": "Temporal only supports min and max.",
    "aggregate_nominal": "Cannot aggregate nominal.",
    "count_q_without_field_1": "Count has to be quantitative and not use a field.",
    "count_q_without_field_2": "Count has to be quantitative and not use a field.",
    "size_nominal": "Size implies order so nominal is misleading.",
    "size_negative": "Do not use size when data is negative as size implies that data is positive.",
    "repeat_channel": "Cannot use single channels twice.",
    "no_encodings": "There has to be at least one encoding. Otherwise, the visualization doesn't show anything.",
    "encoding_no_field_and_not_count": "All encodings (if they have a channel) require field except if we have a count aggregate.",
    "point_tick_bar_without_x_or_y": "Point, tick, and bar require x or y channel.",
    "line_area_without_x_y": "Line and area require x and y channel.",
    "line_area_with_discrete": "Line and area cannot have two discrete.",
    "bar_tick_continuous_x_y": "Bar and tick cannot have both x and y continuous.",
    "bar_tick_area_line_without_continuous_x_y": "Bar, tick, line, area require some continuous variable on x or y.",
    "bar_area_without_zero_1": "Bar and area mark requires scale of continuous to start at zero.",
    "bar_area_without_zero_2": "Bar and area mark requires scale of continuous to start at zero.",
    "size_without_point_text": "Size only works with some marks. Vega-Lite can also size lines, and ticks but that would violate best practices.",
    "same_field_x_and_y": "Don't use the same field on x and y.",
    "count_on_x_and_y": "Don't use count on x and y.",
    "aggregate_not_all_continuous": "If we use aggregation, then all continuous fields need to be aggeragted.",
    "count_twice": "Don't use count twice.",
    "bar_area_overlap": "Bars and area cannot overlap.",
    "stack_without_bar_area": "Only use stacking for bar and area.",
    "stack_without_summative_agg": "Don't stack if aggregation is not summative (summative are count, sum, distinct, valid, missing).",
    "stack_without_discrete_color_1": "Can only use stack if we also use discrete color",
    "stack_without_discrete_color_2": "Can only use stack if we also use discrete color",
    "stack_without_discrete_color_3": "Can only use stack if we also use discrete color",
    "stack_discrete": "Stack can only be on continuous.",
    "stack_without_x_y": "Stack can only be on x or y.",
    "stack_with_non_positional_non_agg": "Cannot use non positional continuous with stack unless it's aggregated.",
    "color_with_cardinality_gt_twenty": "At most 20 categorical colors.",
    "invalid_mark": "Check mark.",
    "invalid_channel": "Check types of encoding properties.",
    "invalid_type": "Check types of encoding properties.",
    "invalid_agg": "Check types of encoding properties.",
    "invalid_bin": "Check types of encoding properties.",

}